import assert from 'node:assert/strict'
const values = new Map<string, string>()
const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => values.set(key, value), removeItem: (key: string) => values.delete(key), key: (index: number) => [...values.keys()][index], get length() { return values.size } }
Object.assign(globalThis, { localStorage: storage, sessionStorage: storage, window: Object.assign(new EventTarget(), { location: { origin: 'http://test.local' } }) })
const bank = await import('../src/database/question-bank')
const { assemblePaper } = await import('../src/lib/question-forge')
const session = bank.resolveSession()
const coverage = bank.coverageForSession(session)
assert.ok(coverage.length >= 4)
const last = coverage.at(-1)!.code
const plan = bank.planForSession(session, { noteCodes: [last], maxQuestions: 4 })
assert.ok(plan.length > 0, 'Selecting a later topic must not lose its budget to earlier topics')
assert.ok(plan.every((row) => row.note.code === last))
assert.deepEqual(bank.planForSession(session, { noteCodes: [], maxQuestions: 4 }), [])
assert.ok(plan.reduce((sum, row) => sum + row.wanted.length, 0) <= 4)
const balanced = bank.planForSession(session, { noteCodes: coverage.slice(0, 4).map((entry) => entry.code), maxQuestions: 4, maxNotes: 4 })
assert.equal(balanced.length, 4, 'A four-question budget should cover all four selected topics')
const pool = bank.questionsForSession(session)
assert.ok(pool.length >= 8)
assert.equal(assemblePaper({ session, questionCount: pool.length + 1 }).paper, null)
assert.equal(assemblePaper({ session, questionCount: 2 }).paper, null)
assert.equal(assemblePaper({ session, timeMinutes: 0 }).paper, null)
const result = assemblePaper({ session, questionCount: 5, timeMinutes: 45 })
assert.equal(result.questions.length, 5)
assert.equal(result.paper?.timeMinutes, 45)
assert.equal(result.paper?.totalMarks, result.questions.reduce((sum, q) => sum + q.marks, 0))
assert.equal(new Set(result.paper?.questionIds).size, 5)
const selectedCodes = [...new Set(pool.slice(0, 4).map(bank.noteCodeFor))]
const scoped = assemblePaper({ session, questionCount: 3, noteCodes: selectedCodes, targetWeakness: false })
assert.equal(scoped.questions.length, 3)
assert.ok(scoped.questions.every((q) => selectedCodes.includes(bank.noteCodeFor(q))))
const batch = bank.recordBatch({ session, questions: [{...pool[0], id: 'regression-draft', origin: 'synthesized'}], noteCodes: [last], model: 'fixture', trigger: 'manual', rejected: 0, status: 'draft' })
assert.ok(!bank.questionsForSession(session).some((q) => q.id === 'regression-draft'))
assert.ok(bank.draftsForSession(session).some((q) => q.id === 'regression-draft'))
bank.acceptBatch(batch.id)
assert.ok(bank.questionsForSession(session).some((q) => q.id === 'regression-draft'))
console.log('PASS: selected-topic planning, empty selection, budget cap, invalid paper sizes, time validation, exact paper length, mark totals, uniqueness, topic scoping, draft isolation and publication')
const { synthesizeQuestions } = await import('../src/lib/question-forge')
const draft = { prompt: 'What constant must be added to an indefinite integral to represent every antiderivative?', type: 'Short response', difficulty: 'Foundation', marks: 2, answer: 'C', accept: { mode: 'equalsAny', values: ['C'] }, steps: ['Differentiate any constant to obtain zero.', 'Add an arbitrary constant C to describe the whole family.'] }
const note = bank.sessionNotes(session)[0]
const abort = new AbortController()
globalThis.fetch = async () => new Response(new ReadableStream({
  start(controller) {
    const data = `data: ${JSON.stringify({ choices: [{ delta: { content: JSON.stringify({ questions: [draft] }) } }] })}\n\n`
    controller.enqueue(new TextEncoder().encode(data))
    abort.signal.addEventListener('abort', () => controller.error(new DOMException('Stopped', 'AbortError')), { once: true })
  },
}), { headers: { 'Content-Type': 'text/event-stream' } })
const stopped = await synthesizeQuestions({session, plan: [{note, wanted:['Foundation'], reason:'test'}], signal:abort.signal, onProgress: (progress) => { if (progress.questions.length) abort.abort() }})
assert.equal(stopped.questions.length, 1, 'Completed drafts survive cancellation')
assert.deepEqual(stopped.noteCodes, [note.code], 'Interrupted streams preserve provenance')
assert.equal(stopped.batch?.status, 'draft')
assert.equal(bank.isGenerating(session), false)
const emptyAbort = new AbortController()
emptyAbort.abort()
const emptyStop = await synthesizeQuestions({session, plan:[{note,wanted:['Foundation'],reason:'test'}], signal:emptyAbort.signal})
assert.equal(emptyStop.questions.length, 0)
assert.match(emptyStop.error ?? '', /stopped/)
console.log('PASS: cancellation preserves completed drafts and provenance; empty cancellation releases generation lock')
